# Generated by Django 3.2.12 on 2022-05-14 07:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
