# Generated by Django 3.2.12 on 2022-05-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouses', '0002_alter_anonymous_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
