# Generated by Django 3.2.12 on 2022-05-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anonymouses', '0003_comment_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymous',
            name='comment_idx',
            field=models.IntegerField(default=0),
        ),
    ]
