# Generated by Django 3.2.12 on 2022-05-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_auto_20220515_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='input',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='type',
            field=models.CharField(default='비밀', max_length=20),
        ),
        migrations.AlterField(
            model_name='solution',
            name='description',
            field=models.TextField(default='.'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='hint',
            field=models.TextField(default='.'),
        ),
    ]
